default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: money_manager
  username: Xin
  password:

test:
  <<: *default
  database: money_manager_test
  username: Xin
  password:

production:
  <<: *default
  database: money_manager_pd
